### ISSUE TITLE
Tap Registered Twice on Touch when setting state inside handler

### ISSUE THREAD

**Issue by elitenoire** [react-spring/react-use-gesture#149]
I have a button in a draggable Card div which I was able to prevent tapping/clicking on the Card div when the button is clicked by stopping propagation on `onMouseDown` & `onTouchStart` Events.

This draggable Card div can also be opened when it is tapped/clicked. I used the `filterTaps` and `tap` to achieve that.

**Problem:**
When you touch-tap on the Card div, it opens twice. I used console logs to measure the `elapsedTime` of the tap and noticed that the second (false) tap lasts for 0ms.

![tap-gesture](https://user-images.githubusercontent.com/25673419/78229531-071f6280-74c8-11ea-9f02-8cdcf43c73d8.jpg)

This happens when the button is nested in between divs. If I remove the divs and leave only the div the gesture is binded to, it works as expected (only a single tap is registered).

**Note:**
Using mouse to click doesn't give that problem, just touching/tapping does.

**Demo:**
I made a minimal Codesandbox demo found [here](https://codesandbox.io/s/charming-cache-7lzx4)

**PS:**
This isn't related to react-use-gesture but can anyone help me to stop the Card div from reaching :active whenever the button is clicked/tapped.

**Comment by dbismut** [comment]
Indeed you're right, thanks for reporting this. I thought I had fixed this but it doesn't look like it. This is because touch devices seem to react to mouseup and mousedown events. I'll see what I can do to filter this out.

**Comment by dbismut** [comment]
Hey @elitenoire try `7.0.7` that I just released and let me know if this works. I really hope this doesn't have too much collateral!

**Comment by dbismut** [comment]
This time it should work @elitenoire

**Comment by elitenoire** [comment]
Thank you for the fix.
It works now.

**Comment by shrugs** [comment]
Hi! I've encountered the same issue, but i'm running `7.0.8`.

here's a pretty minimal codesandbox: https://codesandbox.io/s/focused-chebyshev-bum24 using the `domTarget` approach, and here's one https://codesandbox.io/s/keen-jang-fdeew using `bind`.

the duplicate tap (with ~2ms `elapsedTime` occurs on my physical iphone 11 pro max in both cases.

**Comment by dbismut** [comment]
Damn I can reproduce this. I'll work on a fix. Not easy if I still want this lib to support multiple pointer inputs such as Surface tablets.

**Comment by dbismut** [comment]
@shrugs @elitenoire I've released `7.0.9`, which should fix the problem on all devices. It's an ugly fix, but this comes from touch devices emulating mouse up and down events on clicks. Essentially the logic is:

1. Check if the event is mouse-based
2. If yes, checks if the previous gesture was touch-based
3. If yes, compare start time of the previous gesture and time stamp of the event
4. If the difference is less than 200, then we consider this is an emulated event

So essentially the library now filters mouse gestures that would follow touch gestures too closely. Hope this helps.

**Comment by shrugs** [comment]
confirmed working in my app! much thanks for the fix, and i respect your responsiveness 🙏 

fixed in fab7075447161a5562285dc1f84b733e39434c63

**Comment by elitenoire** [comment]
I updated from `7.0.8` to `7.0.13` and the issue still persists, well from `7.0.9` upwards.

One thing to note that on tap, I'm calling set state which causes a rerendering and I get the false tap.

But without set state, it's working.

Codesandbox with edited code is [here](https://codesandbox.io/s/charming-cache-7lzx4)

Thank you.

**Comment by dbismut** [comment]
@elitenoire hmmm... I see a different issue with dragging on desktop this time. Are you using the Chrome inspector or mobile device?

**Comment by dbismut** [comment]
Ok so this is a better working version of your sandbox:
https://codesandbox.io/s/falling-fire-lthyw?file=/src/index.js

I do see the issue with setState, I'll investigate. Let me change the title of the issue.

**Comment by dbismut** [comment]
I published `7.0.14` with a fix for this @elitenoire.

**Comment by elitenoire** [comment]
Fix works, thank you.
