### ISSUE TITLE
event listener is being called twice

### ISSUE THREAD

**Issue by zvictor** [react-spring/react-use-gesture#24]
The  event listeners for `mousedown` and `touchdown` are being called twice when they are not followed by a drag movement.

As consequence, problems arise with released/nullified synthetic events.

steps to reproduce it (or go to https://codesandbox.io/s/yjj0kp778x):
1- open any demo that uses `useGesture` and the `onAction` method.
2- add `console.log(event.type)` to it
3- perform a single, fast click on the component.

you will see this:
![image](https://user-images.githubusercontent.com/181076/50831095-fa49a880-1330-11e9-8cec-1678c98eb5f1.png)

_bonus step_: add `event.persist()` to the handler in order to get rid of the warning message and be able to see that the event listener is being called twice for the same event.

**Comment by drcmda** [comment]
Do you know how to solve it? I don't have a mouse here right now, using a trackpad. Some users have seen weird effects that things stick to the cursor sometimes, it's probably that.

**Comment by zvictor** [comment]
Unfortunately I couldn't figure out what is causing it, but you should be able to reproduce it even without a mouse. I actually notice it while simulating touch events.

**Comment by williamtstanley** [comment]
I wanted to chime in to add that I am also getting this error on a fork of the `View Pager` example.
![screenshot from 2019-02-12 18-08-04](https://user-images.githubusercontent.com/12862939/52720422-705ab400-2f5c-11e9-9ec1-519281f30886.png)

I just played with a fork again and I get the error after updating the version to 4.0.3,  4.0.0 and 4.0.2 do not have this issue. 4.0.1 has a different error related to 'e' being undefined.

**Comment by drcmda** [comment]
could you link it? would be interesting if it pops up here as well, i haven't seen it for a while.

**Comment by williamtstanley** [comment]
Sorry I totally should have done that. [Sandbox example with error - v4.0.3](https://codesandbox.io/s/rj0z6872rq)

**Comment by drcmda** [comment]
should be fixed, it was due to a new props that's in there, the shift key status, forgot that i need to store it locally due to reacts re-pooling.

**Comment by tim-soft** [comment]
Interestingly I'm still seeing the error with the render props version of 4.0.5, downgrade to 4.0.2 and the error goes away

**Comment by drcmda** [comment]
could you try to trace it? you can copy the source and use it locally for quicker results, it's just one file.

**Comment by tim-soft** [comment]
This line seems to be the culprit https://github.com/react-spring/react-with-gesture/blob/master/index.js#L33
